### ISSUE TITLE
自建host格式提醒不清楚导致crash

### ISSUE THREAD

**Issue by FlyingRadish** [houxg/Leamonax#10]
解决办法: 增加正则检测及提醒

**Comment by xingstarx** [comment]
直接让用户输入URL 如何呢

Ps:  你每天挺刻苦的啊，一直敲代码

**Comment by FlyingRadish** [comment]
现在就是让用户输入url, 不过今天有人因为不知道应该输入什么格式导致一直crash...
@xingstarx 第一个认真挖坑的项目, 另外也算是了了我对为知的怨念了😂

**Comment by houxg** [comment]
6864ce5d7ec39d914a94eabb51dbbe892a934f4b

**Comment by FlyingRadish** [comment]
fixed in:6864ce5d7ec39d914a94eabb51dbbe892a934f4b

**Comment by xingstarx** [comment]
Greate
