### ISSUE TITLE
[Feature]1.1.2测试：默认最后一次的笔记本

### ISSUE THREAD

**Issue by alexwyl** [houxg/Leamonax#12]
感谢更新！
默认最后一次使用的笔记本为新笔记的笔记本，非常好！但如果是间隔比较旧录入新的笔记，会记不住最后一次使用的笔记本，还是需要手工调整，能否改为菜单选择哪个笔记本，就用这个笔记本做为默认笔记，保持和官方pc端一致：选择（点击）笔记本，列出笔记本的笔记，并且新建笔记时默认建在该笔记本下。
谢谢。

**Comment by alexwyl** [comment]
或者这么说吧，1.1.1版本的时候，因为每次都要选笔记本，不容易将笔记保存到错误的笔记本中，1.1.2版本因为有默认值，容易保存错误的笔记本中（因为最近一次使用的不一定是想要的，特别是上次使用间隔比较长了）。也可能是我纠结了。

**Comment by FlyingRadish** [comment]
其实更好的方式是把保存位置显示出来, 而不是藏在某个地方, 不过我还没想好UI上该怎么排版.
使用最近笔记本的逻辑可以适用“最近笔记”, “按tag列出笔记”, 所以不打算对此做更改.
