### ISSUE TITLE
反馈一个横竖屏切换的bug

### ISSUE THREAD

**Issue by AtlantisWing** [houxg/Leamonax#16]
感谢houxg开发的android版
我从1.1.1版本开始使用，但是无意中发现点开一个笔记后再把手机横过来，会显示一个错误，然会退回到列表，重新点开笔记后可以进入，如果再换回竖屏，还是一样的结果。刚刚测试了最新版的1.1.2，问题依旧

错误内容为：全屏变黑，中间出行白色对话框，内容 Unfortunately,Leamonax has stopped.

测试手机为 Sony Z1 Compact 国际版 D5503
谢谢。

**Comment by FlyingRadish** [comment]
这个是没有处理好Activity重建所致，因为涉及到横屏的适配，会暂时限制Leanomax仅支持竖屏方式。

**Comment by xingstarx** [comment]
手机上就应该竖屏，横屏处理是以后考虑的事情额

**Comment by FlyingRadish** [comment]
fix in 063c4a3d1e2ac37cdc61286f807a66224b7e5460
