### ISSUE TITLE
关于大尺寸图片的显示

### ISSUE THREAD

**Issue by AtlantisWing** [houxg/Leamonax#20]
hi～～之前我提了一个横竖屏的bug，因为我有几个笔记里面是一张尺寸比较大的图片
因为不能缩放也不能单独点开，所以需要横屏查看

刚刚看到修复成锁定竖屏了，那是否可以增加图片单独点开并缩放之类的功能～thx～

**Comment by FlyingRadish** [comment]
可以考虑，不过这个的优先级会比较低，当前主要着力点还是解决兼容问题和提高性能

**Comment by xingstarx** [comment]
@houxg 你qq多少啊

**Comment by FlyingRadish** [comment]
@xingstarx 我给你的邮箱发了一封邮件
