### ISSUE TITLE
improve sync mechanism

### ISSUE THREAD

**Issue by FlyingRadish** [houxg/Leamonax#3]
1. first sign in.
2. network is unstable and lead to sync failed finally.
3. some notes still remain because NoteService just save notes to database directly, and these notes will not be deleted if error occurs.

**Comment by xingstarx** [comment]
那你觉得应该怎么设计个同步机制呢

**Comment by FlyingRadish** [comment]
还没有想好，但是大体思路是按最小步进同步。
`notebook`和`note`是共用`usn`的，当前的逻辑是先同步note，再同步notebook，这样遇上弱网络体验会很糟糕。
我觉得可以先同步一部分`note`,再同步对应时期的`notebook`，这样即使是弱网络，但至少可以同步一部分，不至于全部失败。

**Comment by lealife** [comment]
先同步notebooks, 因为notebooks会比较少.
再增量同步notes
最后同步tags

**Comment by FlyingRadish** [comment]
是个好办法~
新的方案是分别记录notebooks, note的last usn，先同步notebook，再同步notes，tag由于还有[缺陷(#461)](https://github.com/leanote/leanote/issues/461)暂时不同步，直接取note中的tag暂时顶着。
@lealife @xingstarx 各位觉得如何？

**Comment by xingstarx** [comment]
恩，可以

**Comment by FlyingRadish** [comment]
resolved in fcf40257b87dfa9d5785123c5badb4ea237df0e2
