### ISSUE TITLE
请问是否停止开发了？

### ISSUE THREAD

**Issue by AtlantisWing** [houxg/Leamonax#30]
非常喜欢那个小白熊的图标～

**Comment by FlyingRadish** [comment]
非常感谢你的欣赏。
目前Leamonax的开发状态确实是处于停滞的，一是我暂时没有精力去维护这个项目，二是Leanote本身也没有更多适合App端的，新的Feature去跟进。
如果你有什么新的想法，欢迎在issue提出

**Comment by AtlantisWing** [comment]
非常感谢你的辛苦开发,现在确实够用了,我本来还以为项目迁移了,或者转为leanote-android继续开发了
马上android要升级8.0了,到时候不知道是否还能继续兼容
另外可否给我下这个小白熊图标的原始图片thx alot~

**Comment by FlyingRadish** [comment]
Leamonax已经被fork到leanote-android，并且会有leanote社区的人进行维护。我会考虑merge那边的fix进来，另外也会加入我个人希望的，但不适宜加到leanote-android的feature（然而现在还没有，也许指纹加密是一个？）
Android 8.0的问题，如果你遇到了兼容问题，欢迎在issue提出，我会尽快修复
Leamonax的Icon其实是我多年前对网上一个藏族阿妈喂食土拨鼠照片的临摹，原件已无法找到，你可以在工程文件找到png格式的图片，请遵循GPL协议使用

**Comment by tr15tan** [comment]
> 非常感谢你的辛苦开发,现在确实够用了,我本来还以为项目迁移了,或者转为leanote-android继续开发了
> 马上android要升级8.0了,到时候不知道是否还能继续兼容
> 另外可否给我下这个小白熊图标的原始图片thx alot~

土拨鼠：谁tm找小白熊？？
哈哈
