### ISSUE TITLE
无法显示笔记

### ISSUE THREAD

**Issue by FlyingRadish** [houxg/Leamonax#5]
hi @xingstarx , 你曾提到无法显示笔记的问题，我找了一个新的js editor，可不可以在[feature/new_editor](https://github.com/houxg/Leamonax/tree/feature/new_editor)试一下？

**Comment by xingstarx** [comment]
恩，好的，我晚上回去试试，最近忙，develop分支上的js editor 我都没有测试过

**Comment by xingstarx** [comment]
其实不是你js editor的问题，而是代码的问题，你的EditorFragment没有做显示title,content的操作

我修改了代码，测试了develop，还有feature/new_editor这两个分支，都可以显示出来。。

调试这个问题太坑爹了。废了好大力气。。

app包下的Fragment，`public void onAttach(Context context) {}` 在我手机上没有执行。不走这个方法，走的其实是`public void onAttach(Activity context) {}` 这个被废弃掉的方法。

我的建议是，现在先暂时解决这个问题，后面的话，都换成v4包下面的fragment，而不是app包下的fragment

你自己手机上看看，有没有执行`onAttach`方法

**Comment by xingstarx** [comment]
#6

**Comment by FlyingRadish** [comment]
原来是这样，我今天用魅族手机的时候碰巧也遇到了这个问题....不过当时还在调Js所以放在一边待解。另外我在Nexus 6P上是正常的。
我在[stackoverflow](http://stackoverflow.com/questions/32083053/android-fragment-onattach-deprecated)看到似乎在API 23(Marshmallow)前后都是正常的...额...
非常感谢你的帮助！

**Comment by xingstarx** [comment]
你也可以把develop分支上的这块改过来，feature/new_editor 看着效果好一些。 我看你最近改动了很多啊，很赞。

**Comment by FlyingRadish** [comment]
Quill确实比原先的editor简洁迅速一些，但还有一些巨坑，希望我能填上...
