### ISSUE TITLE
为什么安卓6.0以下系统安装后无法显示笔记

### ISSUE THREAD

**Issue by nicacol** [houxg/Leamonax#9]
源码编译后，在安卓6.0系统使用正常，但在6.0以下系统，无法显示笔记的内容，请问是怎么回事？

**Comment by xingstarx** [comment]
你是在什么分支下编译的呢

**Comment by nicacol** [comment]
直接下载https://github.com/houxg/Leamonax页面源码编译的






在2016年12月16 09时23分, "xxx"<notifications@github.com>写道:



你是在什么分支下编译的呢

**Comment by xingstarx** [comment]
默认是master 分支额，你想要看最新的功能得切换到develop分支额  
@houxg 可以完善下文档额，方便android码农看最新的功能额

**Comment by FlyingRadish** [comment]
好的，今天完成
